id = "zx"
name = "Ziex"
description = "ZX support."
version = "0.1.0-dev.751"
schema_version = 1
authors = ["Nurul Huda (Apon) <me@nurulhudaapon.com>"]
repository = "https://github.com/nurulhudaapon/ziex"

[language_servers.zls]
name = "zls"
language = "ZX"

[grammars.zx]
repository = "https://github.com/nurulhudaapon/ziex"
rev = "main"
path = "pkg/tree-sitter-zx"

# repository = "file:///Users/nurulhudaapon/Projects/nurulhudaapon/zx"
# rev = "feat/mdzx"

[grammars.mdzx]
repository = "https://github.com/nurulhudaapon/ziex"
rev = "main"
path = "pkg/tree-sitter-mdzx"

# repository = "file:///Users/nurulhudaapon/Projects/nurulhudaapon/zx"
# rev = "feat/mdzx"

[debug_locators.zx-locator]
