id = "ziex"
name = "Ziex"
description = "ZX support."
version = "0.1.1259"
schema_version = 1
authors = ["Nurul Huda (Apon) <me@nurulhudaapon.com>"]
repository = "https://github.com/ziex-dev/ziex"

[language_servers.zxls]
name = "zxls"
language = "ZX"

[grammars.zx]
repository = "https://github.com/ziex-dev/ziex"
rev = "b5208a8c7bdbaae130ff617d9c0f9f1df01e85de"
path = "pkg/tree-sitter-zx"

[grammars.mdzx]
repository = "https://github.com/ziex-dev/ziex"
rev = "b5208a8c7bdbaae130ff617d9c0f9f1df01e85de"
path = "pkg/tree-sitter-mdzx"